pipeline {
    agent {
        docker {
            image 'node:10-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                sh 'docker build . -t aabdelhay/test-app'
                sh 'docker login --username=aabdelhay --email=ahmed.abdelhay@andela.com'
                sh 'docker push aabdelhay/test-app'
            }
        }
    }
}
