pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'export PATH=$PATH:/Users/christopherwebster/.sdkman/candidates/grails/current/bin:/Users/christopherwebster/.sdkman/candidates/gradle/current/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/christopherwebster/springsource/apache-maven-3.0.4/bin:/usr/local/git/bin:/usr/local/bin/npm:/Users/christopherwebster/Dev/google-cloud-sdk/bin:'
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo "delivery will take place here.."'
                //sh './jenkins/scripts/deliver.sh'
                //input message: 'Finished using the web site? (Click "Proceed" to continue)'
                //sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
